import fs from 'fs';
import path from 'path';
import sqlite3 from 'sqlite3';
import { Pool } from 'pg';
import dotenv from 'dotenv';

dotenv.config();

const dbPath = path.join(process.cwd(), 'server', 'database.db');
const DATABASE_URL = process.env.DATABASE_URL;

if (!DATABASE_URL) {
  throw new Error('Falta la variable de entorno DATABASE_URL. Cargala en tu .env antes de ejecutar el script.');
}

const sqlite = new sqlite3.Database(dbPath);
const pgPool = new Pool({ connectionString: DATABASE_URL });

const sqliteQuery = (sql, params = []) =>
  new Promise((resolve, reject) => {
    sqlite.all(sql, params, (err, rows) => {
      if (err) return reject(err);
      resolve(rows);
    });
  });

const pgQuery = async (sql, params = []) => {
  const client = await pgPool.connect();
  try {
    return await client.query(sql, params);
  } finally {
    client.release();
  }
};

const normalizeValue = (value) => {
  if (value === undefined) return null;
  if (value === null) return null;
  if (typeof value === 'number') return value;
  if (typeof value === 'string') return value;
  if (typeof value === 'boolean') return value;
  if (value instanceof Date) return value;
  return value;
};

const tableToColumns = {
  categorias: ['id', 'nombre'],
  clientes: ['id', 'nombre', 'email', 'password_hash', 'rol', 'fecha_registro'],
  productos: ['id', 'nombre', 'descripcion', 'precio', 'stock', 'categoria', 'imagen_url', 'activo', 'destacado', 'orden'],
  pedidos: ['id', 'cliente_id', 'fecha', 'total', 'estado'],
  pedido_items: ['id', 'pedido_id', 'producto_id', 'oferta_id', 'cantidad', 'precio_unitario'],
  mensajes: ['id', 'pedido_id', 'remitente', 'contenido', 'fecha', 'leido', 'hilo_id', 'tipo', 'cerrado'],
  ofertas: ['id', 'nombre', 'producto_ids', 'descuento_o_precio_paquete', 'tipo_descuento', 'prioridad', 'activa', 'desactivada_por_stock', 'producto_sin_stock_id', 'producto_sin_stock_nombre'],
};

const ensureTables = async () => {
  const ddl = `
    CREATE TABLE IF NOT EXISTS categorias (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre VARCHAR(100) NOT NULL UNIQUE
    );

    CREATE TABLE IF NOT EXISTS clientes (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre VARCHAR(255) NOT NULL,
      email VARCHAR(255) NOT NULL UNIQUE,
      password_hash VARCHAR(255) NOT NULL,
      rol VARCHAR(20) NOT NULL DEFAULT 'cliente' CHECK (rol IN ('cliente', 'admin')),
      fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    CREATE TABLE IF NOT EXISTS productos (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre VARCHAR(255) NOT NULL,
      descripcion TEXT,
      precio NUMERIC(10,2) NOT NULL,
      stock INTEGER NOT NULL DEFAULT 0,
      categoria VARCHAR(100) NOT NULL,
      imagen_url TEXT,
      activo BOOLEAN NOT NULL DEFAULT TRUE,
      destacado BOOLEAN NOT NULL DEFAULT FALSE,
      orden INTEGER NOT NULL DEFAULT 0,
      CONSTRAINT fk_productos_categoria FOREIGN KEY (categoria) REFERENCES categorias(nombre)
    );

    CREATE TABLE IF NOT EXISTS pedidos (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cliente_id BIGINT NOT NULL,
      fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      total NUMERIC(10,2) NOT NULL,
      estado VARCHAR(50) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'enviado', 'completado')),
      CONSTRAINT fk_pedidos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id)
    );

    CREATE TABLE IF NOT EXISTS pedido_items (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      pedido_id BIGINT NOT NULL,
      producto_id BIGINT NOT NULL,
      oferta_id BIGINT,
      cantidad INTEGER NOT NULL,
      precio_unitario NUMERIC(10,2) NOT NULL,
      CONSTRAINT fk_pedido_items_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(id),
      CONSTRAINT fk_pedido_items_producto FOREIGN KEY (producto_id) REFERENCES productos(id)
    );

    CREATE TABLE IF NOT EXISTS mensajes (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      pedido_id BIGINT NOT NULL,
      remitente VARCHAR(20) NOT NULL CHECK (remitente IN ('cliente', 'admin')),
      contenido TEXT NOT NULL,
      fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      leido BOOLEAN NOT NULL DEFAULT FALSE,
      hilo_id INTEGER NOT NULL DEFAULT 1,
      tipo VARCHAR(20) NOT NULL DEFAULT 'mensaje' CHECK (tipo IN ('mensaje', 'sistema')),
      cerrado BOOLEAN NOT NULL DEFAULT FALSE,
      CONSTRAINT fk_mensajes_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(id)
    );

    CREATE TABLE IF NOT EXISTS ofertas (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre VARCHAR(255) NOT NULL,
      producto_ids JSONB,
      descuento_o_precio_paquete NUMERIC(10,2) NOT NULL,
      tipo_descuento VARCHAR(50) NOT NULL DEFAULT 'precio_paquete' CHECK (tipo_descuento IN ('precio_paquete', 'porcentaje')),
      prioridad INTEGER NOT NULL DEFAULT 0,
      activa BOOLEAN NOT NULL DEFAULT TRUE,
      desactivada_por_stock BOOLEAN NOT NULL DEFAULT FALSE,
      producto_sin_stock_id BIGINT,
      producto_sin_stock_nombre VARCHAR(255)
    );
  `;

  await pgQuery(ddl);

  await pgQuery(`
    TRUNCATE categorias, clientes, productos, pedidos, pedido_items, mensajes, ofertas RESTART IDENTITY CASCADE;
  `);

  console.log('✅ Estructura de PostgreSQL verificada, tablas destino limpiadas y listas para migrar.');
};

const mapRowToColumns = (row, columns) => {
  const mappedRow = {};

  for (const column of columns) {
    mappedRow[column] = row[column] === undefined ? null : row[column];
  }

  return mappedRow;
};

const migrateTable = async (tableName, references = {}) => {
  const rows = await sqliteQuery(`SELECT * FROM ${tableName}`);

  if (!rows.length) {
    console.log(`✅ Tabla ${tableName}: sin registros para migrar.`);
    return 0;
  }

  const columns = tableToColumns[tableName];
  if (!columns) {
    throw new Error(`No hay columnas definidas para la tabla ${tableName}`);
  }

  const insertSql = `
    INSERT INTO ${tableName} (${columns.join(', ')})
    VALUES (${columns.map((_, index) => `$${index + 1}`).join(', ')})
    ON CONFLICT (id) DO UPDATE SET ${columns
      .filter((column) => column !== 'id')
      .map((column) => `${column} = EXCLUDED.${column}`)
      .join(', ')}
  `;

  let migratedCount = 0;

  for (const row of rows) {
    const mappedRow = mapRowToColumns(row, columns);

    if (tableName === 'pedidos' && mappedRow.cliente_id !== null && !references.clientes?.has(mappedRow.cliente_id)) {
      console.warn(`⚠️ Se omite pedido id=${mappedRow.id} porque cliente_id=${mappedRow.cliente_id} no existe en clientes.`);
      continue;
    }

    if (tableName === 'pedido_items') {
      const pedidoId = mappedRow.pedido_id;
      const productoId = mappedRow.producto_id;
      const ofertaId = mappedRow.oferta_id;

      if (pedidoId !== null && !references.pedidos?.has(pedidoId)) {
        console.warn(`⚠️ Se omite pedido_item id=${mappedRow.id} porque pedido_id=${pedidoId} no existe en pedidos.`);
        continue;
      }

      if (productoId !== null && !references.productos?.has(productoId)) {
        console.warn(`⚠️ Se omite pedido_item id=${mappedRow.id} porque producto_id=${productoId} no existe en productos.`);
        continue;
      }

      if (ofertaId !== null && ofertaId !== undefined && !references.ofertas?.has(ofertaId)) {
        console.warn(`⚠️ Se omite pedido_item id=${mappedRow.id} porque oferta_id=${ofertaId} no existe en ofertas.`);
        continue;
      }
    }

    if (tableName === 'mensajes' && mappedRow.pedido_id !== null && !references.pedidos?.has(mappedRow.pedido_id)) {
      console.warn(`⚠️ Se omite mensaje id=${mappedRow.id} porque pedido_id=${mappedRow.pedido_id} no existe en pedidos.`);
      continue;
    }

    const values = columns.map((column) => normalizeValue(mappedRow[column]));
    await pgQuery(insertSql, values);
    migratedCount += 1;
  }

  console.log(`✅ Tabla ${tableName}: ${migratedCount} registros migrados.`);
  return migratedCount;
};

const migrateAll = async () => {
  try {
    await ensureTables();

    const orderedTables = [
      'categorias',
      'clientes',
      'productos',
      'pedidos',
      'ofertas',
      'pedido_items',
      'mensajes',
    ];

    const references = {
      clientes: new Map(),
      productos: new Map(),
      pedidos: new Map(),
      ofertas: new Map(),
    };

    for (const tableName of orderedTables) {
      const rows = await sqliteQuery(`SELECT * FROM ${tableName}`);
      const tableReferences = new Map();

      for (const row of rows) {
        if (row.id !== undefined && row.id !== null) {
          tableReferences.set(Number(row.id), Number(row.id));
        }
      }

      if (tableName === 'clientes') references.clientes = tableReferences;
      if (tableName === 'productos') references.productos = tableReferences;
      if (tableName === 'pedidos') references.pedidos = tableReferences;
      if (tableName === 'ofertas') references.ofertas = tableReferences;

      await migrateTable(tableName, references);
    }

    console.log('🎉 Migración completa.');
  } catch (error) {
    console.error('❌ Error durante la migración:', error);
    process.exitCode = 1;
  } finally {
    sqlite.close();
    await pgPool.end();
  }
};

migrateAll();
