-- Isolated development database only. Never run against production.
CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  rol VARCHAR(20) NOT NULL DEFAULT 'cliente' CHECK (rol IN ('cliente', 'admin')),
  fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  descripcion TEXT,
  precio NUMERIC(10,2) NOT NULL,
  stock INTEGER NOT NULL DEFAULT 0,
  categoria VARCHAR(100) NOT NULL REFERENCES categorias(nombre),
  imagen_url TEXT,
  imagenes TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  destacado BOOLEAN NOT NULL DEFAULT FALSE,
  orden INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT NOT NULL REFERENCES clientes(id),
  fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  total NUMERIC(10,2) NOT NULL,
  estado VARCHAR(50) NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente','enviado','completado','esperando_aprobacion','pago_rechazado','pendiente_pago','aprobado')),
  metodo_pago VARCHAR(20) NOT NULL DEFAULT 'transferencia' CHECK (metodo_pago IN ('transferencia','efectivo','mercadopago')),
  recargo_aplicado NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (recargo_aplicado >= 0),
  entrega_nombre VARCHAR(120),
  entrega_email VARCHAR(255),
  entrega_telefono VARCHAR(40),
  entrega_direccion VARCHAR(240),
  entrega_notas TEXT,
  envio_destination_id INTEGER,
  envio_localidad VARCHAR(120),
  envio_provincia VARCHAR(120),
  envio_cp VARCHAR(20),
  envio_costo NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (envio_costo >= 0),
  mp_payment_id VARCHAR(80),
  mp_payment_status VARCHAR(40),
  mp_payment_status_detail VARCHAR(120),
  mp_merchant_order_id VARCHAR(120),
  mp_preference_id VARCHAR(120),
  mp_approved_at TIMESTAMPTZ,
  mp_last_webhook_at TIMESTAMPTZ,
  comprobante_url TEXT
);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS entrega_nombre VARCHAR(120);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS entrega_email VARCHAR(255);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS entrega_telefono VARCHAR(40);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS entrega_direccion VARCHAR(240);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS entrega_notas TEXT;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS envio_destination_id INTEGER;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS envio_localidad VARCHAR(120);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS envio_provincia VARCHAR(120);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS envio_cp VARCHAR(20);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS envio_costo NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS mp_payment_id VARCHAR(80);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS mp_payment_status VARCHAR(40);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS mp_payment_status_detail VARCHAR(120);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS mp_merchant_order_id VARCHAR(120);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS mp_preference_id VARCHAR(120);
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS mp_approved_at TIMESTAMPTZ;
ALTER TABLE pedidos ADD COLUMN IF NOT EXISTS mp_last_webhook_at TIMESTAMPTZ;
CREATE UNIQUE INDEX IF NOT EXISTS pedidos_mp_payment_id_unique ON pedidos(mp_payment_id) WHERE mp_payment_id IS NOT NULL;
CREATE TABLE IF NOT EXISTS ofertas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  producto_ids TEXT NOT NULL DEFAULT '[]',
  descuento_o_precio_paquete NUMERIC(10,2) NOT NULL,
  tipo_descuento VARCHAR(50) NOT NULL DEFAULT 'precio_paquete' CHECK (tipo_descuento IN ('precio_paquete','porcentaje')),
  prioridad INTEGER NOT NULL DEFAULT 0,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  desactivada_por_stock BOOLEAN NOT NULL DEFAULT FALSE,
  producto_sin_stock_id BIGINT,
  producto_sin_stock_nombre VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS pedido_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL REFERENCES pedidos(id),
  producto_id BIGINT NOT NULL REFERENCES productos(id),
  oferta_id BIGINT,
  cantidad INTEGER NOT NULL,
  precio_unitario NUMERIC(10,2) NOT NULL
);
CREATE TABLE IF NOT EXISTS mensajes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL REFERENCES pedidos(id),
  remitente VARCHAR(20) NOT NULL CHECK (remitente IN ('cliente','admin')),
  contenido TEXT NOT NULL,
  fecha TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  leido BOOLEAN NOT NULL DEFAULT FALSE,
  hilo_id INTEGER NOT NULL DEFAULT 1,
  tipo VARCHAR(20) NOT NULL DEFAULT 'mensaje' CHECK (tipo IN ('mensaje','sistema')),
  cerrado BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS configuraciones (
  clave VARCHAR(100) PRIMARY KEY,
  valor TEXT NOT NULL DEFAULT ''
);
INSERT INTO configuraciones (clave, valor) VALUES
  ('tienda_nombre', 'NigDiz'),
  ('tienda_whatsapp', ''),
  ('tienda_email_contacto', ''),
  ('tienda_instagram_url', ''),
  ('tienda_direccion', 'Gualeguaychu, Entre Rios'),
  ('tienda_horarios', ''),
  ('tienda_footer_texto', 'Productos pensados para la seguridad, comodidad y felicidad de tus mascotas.')
ON CONFLICT (clave) DO NOTHING;
